Add hopsfs username to mount args
logicalclocks/hopsfs-go-mount pull request #49
Opened 2022-10-28 09:42 UTC by gibchikafa

Passing the hopsfs username allows mounting as any user provided the correct certificates are valid  and the hopsfs username is correct i.e., we do not create the user on the system.

2023-03-23 14:12 UTC, smkniazi requested changes

2023-03-23 14:12 UTC, smkniazi commented on main.go
> +	//<-c.Ready
why it was removed?

2023-03-23 14:12 UTC, smkniazi commented on go.mod
> +replace bazil.org/fuse v0.0.0-20200524192727-fb710f7dfd05 => /home/gibson/work/fuse
?

2023-03-23 14:33 UTC, smkniazi requested changes

2023-03-23 15:11 UTC, gibchikafa commented on Attrs.go
> -	a.Crtime = attrs.Crtime
I am trying o use the latest bazil/fuse library. `Crtime` is deprecated and was removed. Even in the current version is already deprecated.
![Screenshot from 2023-03-23 16-10-42](https://user-images.githubusercontent.com/23209324/227247895-8927ebc0-ac1f-4677-a65b-d85a048a3f89.png)

2023-03-29 10:40 UTC, smkniazi approved these changes

2023-03-29 10:40 UTC, merged