[HOPSFS-153] Add parameters to specify default user and default group in hopsfs-mount
logicalclocks/hopsfs-go-mount pull request #78
Opened 2024-04-16 15:04 UTC by gibchikafa

2024-04-17 08:00 UTC, smkniazi requested changes

2024-04-17 12:48 UTC, gibchikafa commented on internal/hopsfsmount/config.go
> +	if fallBackOwner == "" && fallBackGroup != "" {
maybe the user may aoverride the default with an empty value

2024-04-19 12:44 UTC, gibchikafa commented on internal/hopsfsmount/config.go
> +		if grp == FallBackGroup {
I think  if this check passes then the this group is one of the users groups so it should not return error

2024-04-19 12:54 UTC, smkniazi approved these changes

2024-04-19 12:54 UTC, smkniazi commented on internal/hopsfsmount/config.go
> +		if grp == FallBackGroup {
Yes you are right, I will fix it

2024-04-30 09:37 UTC, merged